services:
  api:
    image: ghcr.io/clintongit/yahdong-api:latest
    env_file: .env
    restart: unless-stopped
    ports:
      - "127.0.0.1:3001:3001"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - internal

  webapp:
    image: ghcr.io/clintongit/yahdong-webapp:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:3080:80"
    networks:
      - internal

networks:
  internal:
    driver: bridge
